services:
  frontend:
    image: ironnicko1413/outfits.ai-frontend:latest
    build:
      context: Frontend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
  backend:
    image: ironnicko1413/outfits.ai-backend:latest
    build:
      context: Go-Backend/
      dockerfile: Dockerfile
    env_file:
      - .env

    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
